### ISSUE TITLE
Failed to load a language-latex2e package grammar

### ISSUE THREAD

**Issue by zoenglinghou** [Aerijo/language-latex2e#13]
[Enter steps to reproduce:]

1. Install the latest release.

**Atom**: 1.23.3 x64
**Electron**: 1.6.15
**OS**: Mac OS X 10.13.3
**Thrown From**: [language-latex2e](https://github.com/Aerijo/language-latex2e) package 0.13.2

### Stack Trace

Failed to load a language-latex2e package grammar

```
At Grammar missing required scopeName property: /Users/CarlosZhang/.atom/packages/language-latex2e/grammars/tree-sitter-latex.cson in /Users/CarlosZhang/.atom/packages/language-latex2e/grammars/tree-sitter-latex.cson

Error: Grammar missing required scopeName property: /Users/CarlosZhang/.atom/packages/language-latex2e/grammars/tree-sitter-latex.cson
    at /Applications/Atom.app/Contents/Resources/app/node_modules/first-mate/lib/grammar-registry.js:128:70
    at /Applications/Atom.app/Contents/Resources/app/node_modules/season/lib/cson.js:223:65
    at tryToString (fs.js:426:3)
    at FSReqWrap.readFileAfterClose [as oncomplete] (fs.js:413:12)
  at /packages/language-latex2e/grammars/tree-sitter-latex.cson:1:1
```

### Commands

```
```

### Non-Core Packages

```
activate-power-mode 2.7.0 
advanced-open-file 0.16.7 
atom-beautify 0.30.9 
atom-clock 0.1.16 
atom-ide-ui 0.8.1 
atom-itunes 0.5.0 
atom-material-syntax 1.0.8 
atom-material-syntax-light 0.4.6 
atom-material-ui 2.1.1 
atom-pair 2.0.13 
atom-toolbar 0.1.6 
atomic-emacs 0.12.1 
auto-encoding 0.7.0 
autocomplete-bibtex 1.1.0 
autocomplete-json 5.5.2 
autocomplete-latex 0.8.1 
autocomplete-python 1.10.5 
busy-signal 1.4.3 
city-lights-syntax 1.1.6 
city-lights-ui 1.3.1 
dictionary 0.5.0 
document-outline 2.0.1 
export-html 3.1.0 
file-icons 2.1.16 
file-templates 0.2.0 
git-plus 7.10.0 
git-plus-toolbar 1.0.1 
git-time-machine 1.5.9 
hey-pane 1.1.0 
Hydrogen 2.2.2 
hydrogen-launcher 1.2.1 
intentions 1.1.5 
language-applescript 0.3.0 
language-arduino 0.4.3 
language-generic-config 1.4.0 
language-latex 1.1.1 
language-latex2e 0.13.2 
language-matlab 0.2.1 
latex 0.49.0 
latex-completions 0.3.3 
latexer 0.3.0 
linter 2.2.0 
linter-chktex 1.3.1 
linter-jsonlint 1.3.0 
linter-markdown 5.2.0 
linter-matlab 1.1.0 
linter-pycodestyle 2.1.3 
linter-shellcheck 1.4.6 
linter-spell 0.15.0 
linter-spell-latex 0.11.0 
linter-ui-default 1.6.10 
linter-write-good 0.9.0 
markdown-preview-plus 2.5.1 
markdown-scroll-sync 2.1.2 
markdown-writer 2.7.3 
merge-conflicts 1.4.5 
minimap 4.29.7 
minimap-autohider 1.5.4 
minimap-cursorline 0.2.0 
minimap-hide 0.3.0 
minimap-linter 2.1.3 
nucleus-dark-ui 0.12.3 
open-recent 5.0.0 
pdf-view 0.64.0 
platformio-ide-terminal 2.8.0 
pretty-json 1.6.4 
python-debugger 0.2.0 
python-tools 0.6.9 
python-yapf 0.14.0 
remote-atom 1.3.12 
restart-atom 0.2.0 
script 3.18.0 
sort-lines 0.18.0 
sync-settings 0.8.3 
teletype 0.7.0 
todo-show 2.1.0 
tool-bar-almighty 0.8.2 
vim-mode-plus 1.28.0 
wordcount 2.10.4 
```

**Comment by Aerijo** [comment]
Were you using dev mode? It was caused by a dev dependency I (probably shouldn't have) left in there. Patch released.

**Comment by zoenglinghou** [comment]
@Aerijo not as far as I know. The only thing that might be related is that I installed [markdown-scroll-sync](https://github.com/vincentcn/markdown-scroll-sync) from github source because their releases are lacking behind.

I also tried reinstalling the package, but it doesn't work.

**Comment by Aerijo** [comment]
@CarlosEvo So my patch didn't work?

**Comment by Aerijo** [comment]
OK. Looking closer at the Error, I see it was because a file in the `grammars` folder was not parsed properly. It was related to the tree-sitter thing I thought it was originally, but somewhat (read: completely) different. I've split the tree-sitter stuff into a different branch, and deleted it from the main one. The patch I just released should work now.

**Comment by zoenglinghou** [comment]
It works perfectly now!!! Thank you for your effort 👍 ❤️

**Comment by khoek** [comment]
I have this error on start upon upgrading to 1.40

**Comment by khoek** [comment]
Oop, just need to rebuild the modules
