### ISSUE TITLE
Update to 0.14.0 fails

### ISSUE THREAD

**Issue by bernd-wechner** [Aerijo/language-latex2e#17]
Am on newly installed Linux Mint 19 system. Installed Atom from a .deb download. Inherited by home folder and ~/.atom folder from prior system (resides on separate disk). Ran Atom, and it notified me of updates. Installed them. Only this one failed with:

```
Updating to “language-latex2e@0.14.0” failed.Hide output…

> tree-sitter-biber@0.0.1 install /tmp/apm-install-dir-118530-16740-rvf83m.s4qrk0ggb9/node_modules/language-latex2e/node_modules/tree-sitter-biber
> node-gyp rebuild

make: Entering directory '/tmp/apm-install-dir-118530-16740-rvf83m.s4qrk0ggb9/node_modules/language-latex2e/node_modules/tree-sitter-biber/build'
  CC(target) Release/obj.target/tree_sitter_biber_binding/src/parser.o
tree_sitter_biber_binding.target.mk:103: recipe for target 'Release/obj.target/tree_sitter_biber_binding/src/parser.o' failed
make: Leaving directory '/tmp/apm-install-dir-118530-16740-rvf83m.s4qrk0ggb9/node_modules/language-latex2e/node_modules/tree-sitter-biber/build'
/tmp/apm-install-dir-118530-16740-rvf83m.s4qrk0ggb9
└── (empty)


In file included from ../src/tree_sitter/parser.h:9:0,
                 from ../src/parser.c:1:
/usr/lib/gcc/x86_64-linux-gnu/7/include/stdint.h:9:16: fatal error: stdint.h: No such file or directory
 # include_next <stdint.h>
                ^~~~~~~~~~
compilation terminated.
make: *** [Release/obj.target/tree_sitter_biber_binding/src/parser.o] Error 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/atom/resources/app/apm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.15.0-23-generic
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-118530-16740-rvf83m.s4qrk0ggb9/node_modules/language-latex2e/node_modules/tree-sitter-biber
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-118530-16740-rvf83m.s4qrk0ggb9/package.json'
npm WARN apm-install-dir-118530-16740-rvf83m.s4qrk0ggb9 No description
npm WARN apm-install-dir-118530-16740-rvf83m.s4qrk0ggb9 No repository field.
npm WARN apm-install-dir-118530-16740-rvf83m.s4qrk0ggb9 No README data
npm WARN apm-install-dir-118530-16740-rvf83m.s4qrk0ggb9 No license field.
npm ERR! Linux 4.15.0-23-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/bernd/.atom/.apm/.apmrc" "--userconfig" "/home/bernd/.atom/.apmrc" "install" "/tmp/d-118530-16740-14ruz66.x9l8y9cnmi/package.tgz" "--runtime=electron" "--target=2.0.3" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! tree-sitter-biber@0.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tree-sitter-biber@0.0.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the tree-sitter-biber package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs tree-sitter-biber
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls tree-sitter-biber
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-118530-16740-rvf83m.s4qrk0ggb9/npm-debug.log
npm ERR! code 1
```
What could be wrong and how can I fix it?

**Comment by bernd-wechner** [comment]
Well, this seemed to help:

` sudo apt install libc6-dev`

but now failing with:

```
Updating to “language-latex2e@0.14.0” failed.Hide output…

> tree-sitter-biber@0.0.1 install /tmp/apm-install-dir-118530-18860-1qda2yk.cmd7czncdi/node_modules/language-latex2e/node_modules/tree-sitter-biber
> node-gyp rebuild

make: Entering directory '/tmp/apm-install-dir-118530-18860-1qda2yk.cmd7czncdi/node_modules/language-latex2e/node_modules/tree-sitter-biber/build'
  CC(target) Release/obj.target/tree_sitter_biber_binding/src/parser.o
  CXX(target) Release/obj.target/tree_sitter_biber_binding/src/binding.o
tree_sitter_biber_binding.target.mk:100: recipe for target 'Release/obj.target/tree_sitter_biber_binding/src/binding.o' failed
make: Leaving directory '/tmp/apm-install-dir-118530-18860-1qda2yk.cmd7czncdi/node_modules/language-latex2e/node_modules/tree-sitter-biber/build'
/tmp/apm-install-dir-118530-18860-1qda2yk.cmd7czncdi
└── (empty)


make: g++: Command not found
make: *** [Release/obj.target/tree_sitter_biber_binding/src/binding.o] Error 127
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/share/atom/resources/app/apm/node_modules/node-gyp/lib/build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Linux 4.15.0-23-generic
gyp ERR! command "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/.bin/node-gyp" "rebuild"
gyp ERR! cwd /tmp/apm-install-dir-118530-18860-1qda2yk.cmd7czncdi/node_modules/language-latex2e/node_modules/tree-sitter-biber
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open '/tmp/apm-install-dir-118530-18860-1qda2yk.cmd7czncdi/package.json'
npm WARN apm-install-dir-118530-18860-1qda2yk.cmd7czncdi No description
npm WARN apm-install-dir-118530-18860-1qda2yk.cmd7czncdi No repository field.
npm WARN apm-install-dir-118530-18860-1qda2yk.cmd7czncdi No README data
npm WARN apm-install-dir-118530-18860-1qda2yk.cmd7czncdi No license field.
npm ERR! Linux 4.15.0-23-generic
npm ERR! argv "/usr/share/atom/resources/app/apm/bin/node" "/usr/share/atom/resources/app/apm/node_modules/npm/bin/npm-cli.js" "--globalconfig" "/home/bernd/.atom/.apm/.apmrc" "--userconfig" "/home/bernd/.atom/.apmrc" "install" "/tmp/d-118530-18860-iya04x.1idzi1kyb9/package.tgz" "--runtime=electron" "--target=2.0.3" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! tree-sitter-biber@0.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tree-sitter-biber@0.0.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the tree-sitter-biber package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs tree-sitter-biber
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls tree-sitter-biber
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /tmp/apm-install-dir-118530-18860-1qda2yk.cmd7czncdi/npm-debug.log
npm ERR! code 1
```

**Comment by bernd-wechner** [comment]
OK

`$ sudo apt install g++`

solved it.

**Comment by Aerijo** [comment]
The dependency it was failing on was (or at least related to) [`tree-sitter`](https://github.com/tree-sitter/tree-sitter), which is necessary for the new grammars I added. 

Thanks for being able to solve this yourself (I had no idea what the solution could be). Hopefully the solutions you gave in this issue can help anyone else who's having problems installing.

**Comment by BambOoxX** [comment]
I also can't install version 0.14.0 on windows. It seems to be related to the version of node that is incompatible with Microsoft building executables.

I checked other issues and stumbled on [this post](https://stackoverflow.com/questions/14278417/cannot-install-node-modules-that-require-compilation-on-windows-7-x64-vs2012/22411007#22411007). 
Apparently, doing `node-gyp rebuild` with some  `--msvs_version=xxxx` option could work.

I do not know where to apply the proposed solution, but someone else may.

```
Updating to “language-latex2e@0.14.0” failed.Hide output…

> tree-sitter-biber@0.0.1 install user\AppData\Local\Temp\apm-install-dir-11875-17232-ejhk07.ssqemf5hfr\node_modules\language-latex2e\node_modules\tree-sitter-biber
> node-gyp rebuild


user\AppData\Local\Temp\apm-install-dir-11875-17232-ejhk07.ssqemf5hfr\node_modules\language-latex2e\node_modules\tree-sitter-biber>if not defined npm_config_node_gyp (node "user\AppData\Local\atom\app-1.29.0\resources\app\apm\node_modules\npm\bin\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "user\AppData\Local\atom\app-1.29.0\resources\app\apm\bin\\..\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 
G�n�ration des projets individuellement dans cette solution. Pour activer la g�n�ration en parall�le, ajoutez le commutateur "/m".
MSBUILD : error MSB4132: La version des outils "2.0" n'est pas reconnue. Les versions disponibles sont "4.0".
user\AppData\Local\Temp\apm-install-dir-11875-17232-ejhk07.ssqemf5hfr
`-- (empty)


gyp ERR! build error 
gyp ERR! stack Error: `C:\Windows\Microsoft.NET\Framework\v4.0.30319\msbuild.exe` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onExit (user\AppData\Local\atom\app-1.29.0\resources\app\apm\node_modules\node-gyp\lib\build.js:276:23)
gyp ERR! stack     at emitTwo (events.js:106:13)
gyp ERR! stack     at ChildProcess.emit (events.js:191:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:215:12)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "user\\AppData\\Local\\atom\\app-1.29.0\\resources\\app\\apm\\bin\\node.exe" "user\\AppData\\Local\\atom\\app-1.29.0\\resources\\app\\apm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd user\AppData\Local\Temp\apm-install-dir-11875-17232-ejhk07.ssqemf5hfr\node_modules\language-latex2e\node_modules\tree-sitter-biber
gyp ERR! node -v v6.9.5
gyp ERR! node-gyp -v v3.4.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'user\AppData\Local\Temp\apm-install-dir-11875-17232-ejhk07.ssqemf5hfr\package.json'
npm WARN apm-install-dir-11875-17232-ejhk07.ssqemf5hfr No description
npm WARN apm-install-dir-11875-17232-ejhk07.ssqemf5hfr No repository field.
npm WARN apm-install-dir-11875-17232-ejhk07.ssqemf5hfr No README data
npm WARN apm-install-dir-11875-17232-ejhk07.ssqemf5hfr No license field.
npm ERR! Windows_NT 10.0.17134
npm ERR! argv "user\\AppData\\Local\\atom\\app-1.29.0\\resources\\app\\apm\\bin\\node.exe" "user\\AppData\\Local\\atom\\app-1.29.0\\resources\\app\\apm\\node_modules\\npm\\bin\\npm-cli.js" "--globalconfig" "user\\.atom\\.apm\\.apmrc" "--userconfig" "user\\.atom\\.apmrc" "install" "user\\AppData\\Local\\Temp\\d-11875-17232-siok18.x28ztlc8fr\\package.tgz" "--runtime=electron" "--target=2.0.5" "--arch=x64" "--global-style"
npm ERR! node v6.9.5
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! tree-sitter-biber@0.0.1 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tree-sitter-biber@0.0.1 install script 'node-gyp rebuild'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the tree-sitter-biber package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs tree-sitter-biber
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls tree-sitter-biber
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     user\AppData\Local\Temp\apm-install-dir-11875-17232-ejhk07.ssqemf5hfr\npm-debug.log
npm ERR! code 1

```
