### ISSUE TITLE
Incompatibility with Atom 1.40.0 on windows 10

### ISSUE THREAD

**Issue by BambOoxX** [Aerijo/language-latex2e#20]
Package install fails on Atom 1.40.0 seemingly due to `tree-sitter`. A re-build of already existing package fails too.

**Install error**
```
Installing “language-latex2e@0.18.0” failed.Hide output…

> tree-sitter-biber@0.5.0 install C:\Users\bob\AppData\Local\Temp\apm-install-dir-119720-3592-1anv23u.hajy\node_modules\language-latex2e\node_modules\tree-sitter-biber
> prebuild-install || node-gyp rebuild


C:\Users\bob\AppData\Local\Temp\apm-install-dir-119720-3592-1anv23u.hajy\node_modules\language-latex2e\node_modules\tree-sitter-biber>if not defined npm_config_node_gyp (node "C:\Users\bob\AppData\Local\atom\app-1.40.0\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\bob\AppData\Local\atom\app-1.40.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 

prebuild-install WARN install No prebuilt binaries found (target=3.1.10 runtime=node arch=x64 libc= platform=win32)
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\bob\AppData\Local\atom\app-1.40.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\bob\AppData\Local\atom\app-1.40.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\configure.js:517:16)
gyp ERR! stack     at C:\Users\bob\AppData\Local\atom\app-1.40.0\resources\app\apm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:182:21)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Users\\bob\\AppData\\Local\\atom\\app-1.40.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\bob\\AppData\\Local\\atom\\app-1.40.0\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\bob\AppData\Local\Temp\apm-install-dir-119720-3592-1anv23u.hajy\node_modules\language-latex2e\node_modules\tree-sitter-biber
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\bob\AppData\Local\Temp\apm-install-dir-119720-3592-1anv23u.hajy\package.json'
npm WARN apm-install-dir-119720-3592-1anv23u.hajy No description
npm WARN apm-install-dir-119720-3592-1anv23u.hajy No repository field.
npm WARN apm-install-dir-119720-3592-1anv23u.hajy No README data
npm WARN apm-install-dir-119720-3592-1anv23u.hajy No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tree-sitter-biber@0.5.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tree-sitter-biber@0.5.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\bob\.atom\.apm\_logs\2019-08-20T08_48_41_328Z-debug.log

```

**Re-build error**
```
prebuild-install WARN install No prebuilt binaries found (target=3.1.10 runtime=node arch=x64 platform=win32)
gyp ERR! clean error 
gyp ERR! stack Error: EPERM: operation not permitted, unlink 'C:\Users\bob\.atom\packages\language-latex2e\node_modules\tree-sitter-biber\build\Release\tree_sitter_biber_binding.node'
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Users\\bob\\AppData\\Local\\atom\\app-1.40.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\bob\\AppData\\Local\\atom\\app-1.40.0\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\bob\.atom\packages\language-latex2e\node_modules\tree-sitter-biber
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tree-sitter-biber@0.5.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tree-sitter-biber@0.5.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\bob\.atom\.apm\_logs\2019-08-20T08_41_40_867Z-debug.log
```

**Comment by Aerijo** [comment]
The 1.40.1 release of Atom should fix this issue.

**Comment by BambOoxX** [comment]
It works as advertised, thanks.

**Comment by BambOoxX** [comment]
@Aerijo it actually popped-up again, with release 1.40.1. I tried to rebuild the package, but it fails. Maybe I should clean the package install, but I am not sure how to proceed.

**Comment by Aerijo** [comment]
@BambOoxX That's odd, it should not have the same error. The original was caused because the environment wasn't set properly, so it couldn't find the right prebuilt binaries. This was patched in 1.40.1, so it shouldn't say `prebuild-install WARN install No prebuilt binaries found (target=3.1.10 runtime=node arch=x64 platform=win32)` anymore.

You can try deleting the folder (`apm uninstall language-latex2e` or going to `~/.atom/packages` and doing it manually), and retrying with `apm install language-latex2e`.

**Comment by BambOoxX** [comment]
Juste deleted and reinstalled (successfully), but after atom restart, an errror pops-up, see below
```
prebuild-install WARN install EBUSY: resource busy or locked, open 'C:\Users\bamboo\.atom\packages\language-latex2e\node_modules\tree-sitter-biber\build\Release\tree_sitter_biber_binding.node'
gyp ERR! clean error 
gyp ERR! stack Error: EPERM: operation not permitted, unlink 'C:\Users\bamboo\.atom\packages\language-latex2e\node_modules\tree-sitter-biber\build\Release\tree_sitter_biber_binding.node'
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Users\\bamboo\\AppData\\Local\\atom\\app-1.40.1\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\bamboo\\AppData\\Local\\atom\\app-1.40.1\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\bamboo\.atom\packages\language-latex2e\node_modules\tree-sitter-biber
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tree-sitter-biber@0.5.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tree-sitter-biber@0.5.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by Aerijo** [comment]
It may be a caching issue; Atom will (helpfully) cache which native modules a package needs, so it can check if they support the current Atom version. Unfortunately, it doesn't invalidate the cache, so an error can stick.

Could you try
1. Uninstalling this package
2. Restarting Atom
3. Opening dev tools (`ctrl-shift-i`)
4. In the top tabs (Element, Console, etc.) pick "Application"
5. In the left sidebar, expand Local Storage and click the `file://` or whatever entry is there. It should bring up a table of key-value pairs
6. Filter to `language-latex2e` and delete the entry (or entries) that look like
```
installed-packages:language-latex2e:0.18.0:electron-3.1.10:incompatible-native-modules
```
7. Close Atom and reinstall `language-latex2e`
8. See if that works.

**Comment by BambOoxX** [comment]
Following your procedure works just fine ! Thanks a lot. A side note, a
```
installed-packages:language-latex2e:0.18.0:electron-3.1.10:incompatible-native-modules
```
remains in the list, but with empty value.

**Comment by Aerijo** [comment]
Yeah, that’s fine.

**Comment by BambOoxX** [comment]
The same error occured with Atom 1.41. But the previous fix seems to not work here. 

```
> tree-sitter-biber@0.5.0 install C:\Users\bamboo\AppData\Local\Temp\apm-install-dir-119924-840-1pkvyb0.wl8b\node_modules\language-latex2e\node_modules\tree-sitter-biber
> prebuild-install || node-gyp rebuild


C:\Users\bamboo\AppData\Local\Temp\apm-install-dir-119924-840-1pkvyb0.wl8b\node_modules\language-latex2e\node_modules\tree-sitter-biber>if not defined npm_config_node_gyp (node "C:\Users\bamboo\AppData\Local\atom\app-1.41.0\resources\app\apm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\bamboo\AppData\Local\atom\app-1.41.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild ) 

prebuild-install WARN install No prebuilt binaries found (target=4.2.7 runtime=electron arch=x64 libc= platform=win32)
gyp ERR! configure error 
gyp ERR! stack Error: Can't find Python executable "C:\Program Files\Python27\python.exe", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\bamboo\AppData\Local\atom\app-1.41.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\configure.js:492:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\bamboo\AppData\Local\atom\app-1.41.0\resources\app\apm\node_modules\npm\node_modules\node-gyp\lib\configure.js:517:16)
gyp ERR! stack     at C:\Users\bamboo\AppData\Local\atom\app-1.41.0\resources\app\apm\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:182:21)
gyp ERR! System Windows_NT 10.0.18362
gyp ERR! command "C:\\Users\\bamboo\\AppData\\Local\\atom\\app-1.41.0\\resources\\app\\apm\\bin\\node.exe" "C:\\Users\\bamboo\\AppData\\Local\\atom\\app-1.41.0\\resources\\app\\apm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\bamboo\AppData\Local\Temp\apm-install-dir-119924-840-1pkvyb0.wl8b\node_modules\language-latex2e\node_modules\tree-sitter-biber
gyp ERR! node -v v10.2.1
gyp ERR! node-gyp -v v3.7.0
gyp ERR! not ok 
npm WARN enoent ENOENT: no such file or directory, open 'C:\Users\bamboo\AppData\Local\Temp\apm-install-dir-119924-840-1pkvyb0.wl8b\package.json'
npm WARN apm-install-dir-119924-840-1pkvyb0.wl8b No description
npm WARN apm-install-dir-119924-840-1pkvyb0.wl8b No repository field.
npm WARN apm-install-dir-119924-840-1pkvyb0.wl8b No README data
npm WARN apm-install-dir-119924-840-1pkvyb0.wl8b No license field.

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! tree-sitter-biber@0.5.0 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the tree-sitter-biber@0.5.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\bamboo\.atom\.apm\_logs\2019-10-24T07_57_52_131Z-debug.log
```

**Comment by Aerijo** [comment]
@BambOoxX I've updated the prebuilds of the native modules, can you try with version 0.18.1?

**Comment by BambOoxX** [comment]
@Aerijo , works like a charm now, thanks a lot !
